[project]
name = "melting-point"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.4",
    "optuna>=4.5.0",
    "pandas>=2.3.3",
    "rdkit>=2025.9.1",
    "scikit-learn>=1.7.2",
    "xgboost>=3.1.0",
]
